# =================================================================
# Docker Compose para Mautic 5 con Plugin Amazon SES Personalizado
# Optimizado para despliegue en Portainer desde un Repositorio Git
# =================================================================

services:
  db:
    image: mysql:8.0
    container_name: mautic_db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD ping
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - mautic-net

  mautic:
    # Construye la imagen desde el Dockerfile en la raíz del repositorio.
    build: .
    # Opcional: Dale un nombre a la imagen construida para identificarla fácilmente.
    image: mautic-custom-ses:5.0.4
    container_name: mautic_web
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${MAUTIC_PORT_HOST}:80"
    volumes:
      - mautic-config:/etc/mautic
      - mautic-logs:/var/www/html/var/logs
      - mautic-media-files:/var/www/html/media/files
      - mautic-media-images:/var/www/html/media/images
    environment:
      - MAUTIC_DB_HOST=db
      - MAUTIC_DB_USER=${MYSQL_USER}
      - MAUTIC_DB_PASSWORD=${MYSQL_PASSWORD}
      - MAUTIC_DB_NAME=${MYSQL_DATABASE}
      - MAUTIC_URL=${MAUTIC_URL}
      - MAUTIC_MAILER_FROM_NAME=${MAUTIC_MAILER_FROM_NAME}
      - MAUTIC_MAILER_FROM_EMAIL=${MAUTIC_MAILER_FROM_EMAIL}
      - MAUTIC_DEFAULT_TIMEZONE=${MAUTIC_DEFAULT_TIMEZONE}
      - MAUTIC_ADMIN_EMAIL=${MAUTIC_ADMIN_EMAIL}
      - MAUTIC_ADMIN_PASSWORD=${MAUTIC_ADMIN_PASSWORD}
    networks:
      - mautic-net

  mautic_cron:
    # Usa la misma imagen construida para el servicio principal.
    build: .
    image: mautic-custom-ses:5.0.4
    container_name: mautic_cron
    volumes:
      - mautic-config:/etc/mautic
      - mautic-logs:/var/www/html/var/logs
      - mautic-media-files:/var/www/html/media/files
      - mautic-media-images:/var/www/html/media/images
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_cron
      - MAUTIC_DB_HOST=db
      - MAUTIC_DB_USER=${MYSQL_USER}
      - MAUTIC_DB_PASSWORD=${MYSQL_PASSWORD}
      - MAUTIC_DB_NAME=${MYSQL_DATABASE}
    depends_on:
      mautic:
        condition: service_started
    networks:
      - mautic-net

volumes:
  mysql-data:
  mautic-config:
  mautic-logs:
  mautic-media-files:
  mautic-media-images:

networks:
  mautic-net: {}
